/**
 * data.js — Dados embutidos de fallback (CORRIGIDO)
 * ─────────────────────────────────────────────────────────────────────────────
 * Combina DESLIGAMENTOS e ADMISSÕES em um único CSV (window.EMBEDDED_DATA)
 * com colunas uniformes que o app.js consegue processar.
 *
 * Colunas: COLABORADOR, SUPERVISOR, CARGO, MUNICIPIO, LOJA, MES, ANO, STATUS, STATUS_PROCESSO
 *   STATUS          → "DEMISSÃO" para desligamentos | "ADMISSÃO" para admissões
 *   STATUS_PROCESSO → status operacional do processo (desligamento ou admissão)
 *
 * Fonte: DEMISSÕES / ADMISSÕES.xlsx
 * Exportado em: 15/06/2026
 * DESLIGAMENTOS: 118 registros | ADMISSÕES: 101 registros
 */

window.EMBEDDED_DATA = `COLABORADOR,SUPERVISOR,CARGO,MUNICIPIO,LOJA,MES,ANO,STATUS,STATUS_PROCESSO
LILIAN DE SOUZA BARRETO DA SILVA,ALYSSON,BALCONISTA,FSA,4,OUT,2025,DEMISSÃO,Finalizado
FERNANDA BATISTA DOS SANTOS,MAICON,CAIXA,SSA,20,OUT,2025,DEMISSÃO,Finalizado
CATIA PEREIRA GONCALVES,MARCELLO,BALCONISTA,FSA,1,NOV,2025,DEMISSÃO,Finalizado
DANIELA NASCIMENTO SANTANA,MARCELLO,BALCONISTA,SAJ,24,NOV,2025,DEMISSÃO,Finalizado
ESDRAS FERREIRA DOS SANTOS,MARCELLO,BALCONISTA,SAJ,24,NOV,2025,DEMISSÃO,Finalizado
JANAINA JESUS DA SILVA,MAICON,BALCONISTA,SSA,18,NOV,2025,DEMISSÃO,Finalizado
JANIO SILVA NERY,RAFAEL,BALCONISTA,SSA,10,NOV,2025,DEMISSÃO,Finalizado
SALOME DE OLIVEIRA BATISTA,ALYSSON,CAIXA,FSA,13,NOV,2025,DEMISSÃO,Finalizado
JOANA SOARES RODRIGUES,MARCELLO,BALCONISTA,SAJ,6,NOV,2025,DEMISSÃO,Finalizado
RAFAEL AZEVEDO VITORIA,MAICON,FARMACEUTICO,SSA,20,NOV,2025,DEMISSÃO,Finalizado
GABRIEL COSTA BACELAR,MARCELLO,CAIXA,FSA,15,NOV,2025,DEMISSÃO,Finalizado
SIDINEA REIS DOS SANTOS,MAICON,BALCONISTA,SSA,20,NOV,2025,DEMISSÃO,Finalizado
EMANUELLE VITORIA DA CONCEICAO CUNHA EVANGELISTA,ALYSSON,CAIXA,FSA,13,NOV,2025,DEMISSÃO,Finalizado
VIVIANE REIS MASCARENHAS,ALYSSON,BALCONISTA,FSA,8,NOV,2025,DEMISSÃO,Finalizado
MARCIA DE JESUS FERREIRA,RAFAEL,BALCONISTA,SSA,22,NOV,2025,DEMISSÃO,Finalizado
UESLEI CARVALHO DE OLIVEIRA DOS SANTOS,MAICON,CAIXA,SSA,17,NOV,2025,DEMISSÃO,Finalizado
BIANCA MARQUES SILVA,MAICON,CAIXA,SSA,23,NOV,2025,DEMISSÃO,Finalizado
LAISA GRASIELE SANTOS DE OLIVEIRA,MAICON,BALCONISTA,SSA,20,DEZ,2025,DEMISSÃO,Finalizado
ELIZANA DE MATOS MIRANDA DOS SANTOS,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,DEMISSÃO,Finalizado
SAMARA DOS SANTOS VIEIRA,RAFAEL,CAIXA,SSA,12,DEZ,2025,DEMISSÃO,Finalizado
PEDRO GILBERTO PIRES DE ARAGAO NETO,RAFAEL,CAIXA,SSA,25,DEZ,2025,DEMISSÃO,Finalizado
NICOLE GABRIELE BRANDI BARBOZA,ALYSSON,CAIXA,FSA,11,DEZ,2025,DEMISSÃO,Finalizado
DANIEL COUTINHO NERES DE JESUS,ALYSSON,GERENTE,FSA,3,DEZ,2025,DEMISSÃO,Finalizado
BIANCA BARBOSA DE OLIVEIRA,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,DEMISSÃO,Finalizado
EMILLY CORREIA OLIVEIRA,ALYSSON,CAIXA,FSA,13,DEZ,2025,DEMISSÃO,Finalizado
ABRAAO BATISTA SANTOS,MAICON,CAIXA,SSA,20,DEZ,2025,DEMISSÃO,Finalizado
ELISANGELA SANTOS SILVA,MARCELLO,BALCONISTA,SAJ,6,DEZ,2025,DEMISSÃO,Finalizado
MARILIA DE SANTANA SOUZA,MAICON,BALCONISTA,SSA,17,DEZ,2025,DEMISSÃO,Finalizado
JAISMILE DO NASCIMENTO SAMPAIO GUERRA,MARCELLO,BALCONISTA,FSA,1,DEZ,2025,DEMISSÃO,Finalizado
AMANDA SOUZA ROLIM,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,DEMISSÃO,Finalizado
IEDA BARBOSA DE JESUS SANTOS,RAFAEL,BALCONISTA,SSA,12,DEZ,2025,DEMISSÃO,Finalizado
GUILHERME PEREIRA CERQUEIRA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,DEZ,2025,DEMISSÃO,Finalizado
MAURICIO PAIXAO SERRA SOUZA,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,DEMISSÃO,Finalizado
LAIS STEPHANIE SILVA DANTAS,ALYSSON,CAIXA,FSA,13,DEZ,2025,DEMISSÃO,Finalizado
PEDRO PAULO SOUZA LOBO,MARCELLO,BALCONISTA,SAJ,24,DEZ,2025,DEMISSÃO,Finalizado
RAYANE REIS CUNHA CERQUEIRA,ALYSSON,FARMACEUTICO,FSA,8,DEZ,2025,DEMISSÃO,Finalizado
SUZANA SANTOS DA SILVA,RAFAEL,FARMACEUTICO,SSA,12,JAN,2026,DEMISSÃO,Finalizado
VINICIUS EDUARDO CERQUEIRA SANTOS,MARCELLO,CAIXA,FSA,15,JAN,2026,DEMISSÃO,Finalizado
BARBARA DE ARAUJO SILVA,ALYSSON,CAIXA,FSA,8,JAN,2026,DEMISSÃO,Finalizado
CLAUDIO ALBUQUERQUE BRITO SILVA,ALYSSON,BALCONISTA,FSA,14,JAN,2026,DEMISSÃO,Finalizado
IVIA RIBEIRO DE JESUS,RAFAEL,BALCONISTA,SSA,21,JAN,2026,DEMISSÃO,Finalizado
CRELIO JOSE SANTANA,MAICON,FARMACEUTICO,SSA,23,JAN,2026,DEMISSÃO,Finalizado
PALOMA MACEDO DE SANTANA,ALYSSON,BALCONISTA,FSA,2,JAN,2026,DEMISSÃO,Finalizado
JULIANA SILVA DE ASSIS,MARCELLO,CAIXA,SAJ,24,JAN,2026,DEMISSÃO,Finalizado
JULIA DOS SANTOS FARIAS,RAFAEL,BALCONISTA,SSA,25,JAN,2026,DEMISSÃO,Finalizado
LAIZA PRAXEDES DOS SANTOS MARTINS,RAFAEL,CAIXA,SSA,10,JAN,2026,DEMISSÃO,Finalizado
DIEGO CHAVES DA SILVA,RAFAEL,GERENTE,SSA,30,JAN,2026,DEMISSÃO,Finalizado
VALERIA SANTOS SOUZA,MARCELLO,BALCONISTA,CAC,5,JAN,2026,DEMISSÃO,Finalizado
INGRID ALVES DOS SANTOS,RAFAEL,CAIXA,SSA,12,FEV,2026,DEMISSÃO,Finalizado
QUEZIA GABRIELLE CARDIM SANTOS,MARCELLO,BALCONISTA,VAL,16,FEV,2026,DEMISSÃO,Finalizado
AMANDA SILVA OLIVEIRA,MARCELLO,CAIXA,SAJ,27,FEV,2026,DEMISSÃO,Finalizado
JOAO GABRIEL NUNES MOREIRA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,DEMISSÃO,Finalizado
DAVI GOES DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,FEV,2026,DEMISSÃO,Finalizado
JEREMIAS PRAZERES SALES SANTOS,ALYSSON,CAIXA,FSA,11,FEV,2026,DEMISSÃO,Finalizado
MIRIAN PEREIRA DE OLIVEIRA,MARCELLO,BALCONISTA,FSA,15,MAR,2026,DEMISSÃO,Finalizado
CARLOS DANIEL SANTOS ALMEIDA,MARCELLO,BALCONISTA,FSA,1,MAR,2026,DEMISSÃO,Finalizado
JULIANA SILVA DOS SANTOS,MARCELLO,BALCONISTA,SAJ,27,MAR,2026,DEMISSÃO,Finalizado
TIELLE VICTORIA DIAS DOS SANTOS,MAICON,BALCONISTA,SSA,23,MAR,2026,DEMISSÃO,Finalizado
ANA PAULA BASTOS DE OLIVEIRA,MAICON,BALCONISTA,SSA,17,MAR,2026,DEMISSÃO,Finalizado
ERIVALDO BRASILEIRO VITOR,MAICON,BALCONISTA,SSA,19,MAR,2026,DEMISSÃO,Finalizado
ATANASIA TRINDADE CONCEICAO,RAFAEL,BALCONISTA,SSA,21,MAR,2026,DEMISSÃO,Finalizado
JURANDIR BRITO RIBEIRO,RAFAEL,BALCONISTA,SSA,12,MAR,2026,DEMISSÃO,Finalizado
FERNANDA GONCALVES DIAS,MAICON,BALCONISTA,SSA,18,MAR,2026,DEMISSÃO,Finalizado
JONATHAS RIBEIRO PEREIRA,MARCELLO,BALCONISTA,VAL,29,MAR,2026,DEMISSÃO,Finalizado
JAILZA CARVALHO DE ALMEIDA,ALYSSON,BALCONISTA,FSA,4,MAR,2026,DEMISSÃO,Finalizado
JILVANICE SILVA DO NASCIMENTO,ALYSSON,BALCONISTA,FSA,4,MAR,2026,DEMISSÃO,Finalizado
JAMILE SILVA DE SENA,ALYSSON,BALCONISTA,FSA,8,MAR,2026,DEMISSÃO,Finalizado
PABLINE DE JESUS DA CRUZ,ALYSSON,BALCONISTA,FSA,8,MAR,2026,DEMISSÃO,Finalizado
ALANE PEREIRA OLIVEIRA,ALYSSON,BALCONISTA,FSA,3,MAR,2026,DEMISSÃO,Finalizado
DANIEL CAVALCANTE BORGES,ALYSSON,BALCONISTA,FSA,13,MAR,2026,DEMISSÃO,Finalizado
MARIA EDUARDA CARVALHO DOS SANTOS,MAICON,BALCONISTA,SSA,17,MAR,2026,DEMISSÃO,Finalizado
ANDREY DE ABREU GUSMAO,RAFAEL,BALCONISTA,SSA,12,MAR,2026,DEMISSÃO,Finalizado
OHANA TEIXEIRA DA SILVA,MARCELLO,BALCONISTA,FSA,15,MAR,2026,DEMISSÃO,Finalizado
REIGIANE MATOS DOS SANTOS SILVA,MAICON,BALCONISTA,JAC,28,MAR,2026,DEMISSÃO,Finalizado
BRENDA FIGUEIREDO SANTO ROCHA SILVA,MAICON,CAIXA,SSA,23,MAR,2026,DEMISSÃO,Finalizado
VITORIA CRUZ BASTOS,ALYSSON,BALCONISTA,FSA,14,MAR,2026,DEMISSÃO,Finalizado
DEISIANE CRISTINA SANTOS DA SILVA DOS SANTOS,RAFAEL,BALCONISTA,SSA,12,ABR,2026,DEMISSÃO,Pendente pagamento
RITA DE CASSIA SILVA SANTOS,ISAAC,BALCONISTA,FSA,9,ABR,2026,DEMISSÃO,Em andamento
ANDRE COSTA MORAIS,RAFAEL,GERENTE,SSA,25,ABR,2026,DEMISSÃO,Pendente documento
GEOVANA SILVA SANTANA,MAICON,BALCONISTA,JAC,28,ABR,2026,DEMISSÃO,Em andamento
CAIO ARTUR BARRETO DOS SANTOS,MARCELLO,CAIXA,FSA,1,ABR,2026,DEMISSÃO,Finalizado
IARA DE FREITAS MOREIRA,RAFAEL,BALCONISTA,SSA,30,ABR,2026,DEMISSÃO,Assinatura pendente
EMILY PAIM SOUSA MARTINS,MAICON,CAIXA,SSA,31,ABR,2026,DEMISSÃO,Finalizado
ALEXSANDRO GOUVEIA FRANCO,MAICON,CAIXA,SSA,18,ABR,2026,DEMISSÃO,Em andamento
EMILY DOS REIS ALMEIDA,MARCELLO,CAIXA,FSA,15,ABR,2026,DEMISSÃO,Finalizado
KARINE SACRAMENTO GARRIDO,MARCELLO,CAIXA,SAJ,24,ABR,2026,DEMISSÃO,Finalizado
JEFFERSON VIEIRA BOAVENTURA,MARCELLO,CAIXA,VAL,29,ABR,2026,DEMISSÃO,Pendente documento
GABRIEL DOS SANTOS SILVA,RAFAEL,CAIXA,SSA,22,ABR,2026,DEMISSÃO,Travado
JESSICA SANTOS DA SILVA,MARCELLO,CAIXA,FSA,1,ABR,2026,DEMISSÃO,Finalizado
MARIA PAULA DE OLIVEIRA DIAS,ALYSSON,CAIXA,FSA,8,ABR,2026,DEMISSÃO,Finalizado
CARLOS ROBERTO OLIVEIRA BOTELHO,RAFAEL,CAIXA,SSA,22,ABR,2026,DEMISSÃO,Assinatura pendente
EUGENIO LUCAS MELO SILVA,ALYSSON,BALCONISTA,FSA,14,MAR,2026,DEMISSÃO,Finalizado
DEILSON NIEL DA PAIXAO SILVA,MAICON,BALCONISTA,SSA,18,MAI,2026,DEMISSÃO,Pendente pagamento
JOSELILYAN DOS SANTOS BRAGA,MARCELLO,BALCONISTA,VAL,29,MAI,2026,DEMISSÃO,Em andamento
LETICIA DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,MAI,2026,DEMISSÃO,Pendente documento
EVELYN SANTOS REIS,ALYSSON,CAIXA,FSA,4,MAI,2026,DEMISSÃO,Em andamento
EVERTON DOS SANTOS FERREIRA,ALYSSON,CAIXA,FSA,14,MAI,2026,DEMISSÃO,Pendente pagamento
MARIA VITORIA LIMA DA SILVA,ALYSSON,CAIXA,FSA,11,MAI,2026,DEMISSÃO,Em andamento
DJALMA DA HORA SILVA JUNIOR,RAFAEL,CAIXA,SSA,10,MAI,2026,DEMISSÃO,Assinatura pendente
WELBER SANTOS PLINIO JUNIOR,RAFAEL,BALCONISTA,SSA,30,MAI,2026,DEMISSÃO,Pendente pagamento
GIRLENE SILVA DO EVANGELHO,ISAAC,ADMINISTRATIVO,FSA,9,MAI,2026,DEMISSÃO,Em andamento
MACIA VITAL BENTO,MAICON,BALCONISTA,SSA,17,MAI,2026,DEMISSÃO,Travado
LUDMILA CARVALHO DE JESUS SANTOS,MAICON,CAIXA,SSA,20,MAI,2026,DEMISSÃO,Pendente documento
LUNA CARLA BARBOSA SANTOS CARDOSO,MAICON,CAIXA,SSA,23,MAI,2026,DEMISSÃO,Em andamento
ANDRE DE JESUS SUZART,RAFAEL,CAIXA,SSA,30,MAI,2026,DEMISSÃO,Pendente pagamento
ANA CATARINA DA SILVA NASCIMENTO,RAFAEL,CAIXA,SSA,25,MAI,2026,DEMISSÃO,Em andamento
JEFFERSON DOS SANTOS SOUZA SANTANA,MARCELLO,BALCONISTA,CAC,5,MAI,2026,DEMISSÃO,Assinatura pendente
SILMARA SANTOS BARBOSA,ALYSSON,BALCONISTA,FSA,13,MAI,2026,DEMISSÃO,Em andamento
ELIZABETE SANTANA DA SILVA,MARCELLO,BALCONISTA,VAL,29,MAI,2026,DEMISSÃO,Pendente documento
EMANUELLE DE OLIVEIRA,RAFAEL,BALCONISTA,SSA,12,MAI,2026,DEMISSÃO,Pendente pagamento
MARIA EDUARDA ALVES MORAIS,MARCELLO,BALCONISTA,FSA,15,MAI,2026,DEMISSÃO,Em andamento
ROSEKELLY RODRIGUES RIBEIRO,MARCELLO,CAIXA,FSA,1,JUN,2026,DEMISSÃO,Pendente documento
NAYANA DHENYFER CARVALHO DOS SANTOS,MARCELLO,BALCONISTA,SAJ,27,JUN,2026,DEMISSÃO,Iniciado
LORENA NICOLY SOUZA SAMPAIO DE ALMEIDA,ALYSSON,BALCONISTA,FSA,26,JUN,2026,DEMISSÃO,Pendente
YASMIN CERQUEIRA SOBRAL,ALYSSON,CAIXA,FSA,26,JUN,2026,DEMISSÃO,Iniciado
BEATRIZ RAVELLY BOAVENTURA BARNABE,ALYSSON,BALCONISTA,FSA,3,JUN,2026,DEMISSÃO,Em andamento
CAMILA OLIVEIRA CHAVES,ALYSSON,BALCONISTA,FSA,3,JUN,2026,DEMISSÃO,Pendente pagamento
RAISSA KELLY CARVALHO MOREIRA,ALYSSON,BALCONISTA,FSA,11,JUN,2026,DEMISSÃO,Pendente documento
IARA NEVES DE CARVALHO,MAICON,CAIXA,SSA,23,NOV,2025,ADMISSÃO,Finalizado
DEILSON NIEL DA PAIXAO SILVA,MAICON,BALCONISTA,SSA,17,NOV,2025,ADMISSÃO,Finalizado
MARIA EDUARDA CARVALHO,RAFAEL,BALCONISTA,SSA,22,NOV,2025,ADMISSÃO,Finalizado
LAIZA PRAXEDES DOS SANTOS MARTINS,RAFAEL,CAIXA,SSA,10,NOV,2025,ADMISSÃO,Finalizado
LIVIA DE ATAIDE DOS SANTOS,MAICON,CAIXA,SSA,18,NOV,2025,ADMISSÃO,Finalizado
ELISANGELA SANTO SILVA,MARCELLO,BALCONISTA,SAJ,6,NOV,2025,ADMISSÃO,Finalizado
ISYS GABRIELY REBOUCAS CONCEICAO,MARCELLO,CAIXA,SAJ,6,NOV,2025,ADMISSÃO,Finalizado
ELLEN VICTORIA PEREIRA FREITAS,ALYSSON,CAIXA,FSA,13,NOV,2025,ADMISSÃO,Finalizado
AMANDA SOUZA ROLIM,ALYSSON,CAIXA,FSA,8,DEZ,2025,ADMISSÃO,Finalizado
LILIAN DA LUZ SANTOS,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,ADMISSÃO,Finalizado
BARBARA SUELLEN MORENO LEAO DOS SANTOS EVANGELISTA,ALYSSON,CAIXA,FSA,11,DEZ,2025,ADMISSÃO,Finalizado
JEREMIAS PRAZERES SALES SANTOS,ALYSSON,BALCONISTA,FSA,11,DEZ,2025,ADMISSÃO,Finalizado
LUDYMILLA SENA DO NASCIMENTO,MARCELLO,CAIXA,FSA,15,DEZ,2025,ADMISSÃO,Finalizado
ANDRE COSTA MORAIS,RAFAEL,BALCONISTA,SSA,25,DEZ,2025,ADMISSÃO,Finalizado
LILIAN DA LUZ SANTOS,MARCELLO,BALCONISTA,FSA,7,DEZ,2025,ADMISSÃO,Finalizado
DAVI GOES DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,DEZ,2025,ADMISSÃO,Finalizado
AMANDA SOUZA ROLIM,ALYSSON,CAIXA,FSA,8,DEZ,2025,ADMISSÃO,Finalizado
THAYNA SILVA DE SOUSA,MARCELLO,CAIXA,FSA,1,DEZ,2025,ADMISSÃO,Finalizado
KAMILY NUNES DOS SANTOS,MARCELLO,CAIXA,SAJ,6,DEZ,2025,ADMISSÃO,Finalizado
MIGUEAS SANTANA SILVA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,DEZ,2025,ADMISSÃO,Finalizado
VALERIA SANTOS SOUZA,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,ADMISSÃO,Finalizado
EDUARDO SOUZA NEVES,MARCELLO,BALCONISTA,SAJ,24,DEZ,2025,ADMISSÃO,Finalizado
MARIELLE DE JESUS MOREIRA,ALYSSON,BALCONISTA,FSA,13,DEZ,2025,ADMISSÃO,Finalizado
MARIA VITORIA LIMA DA SILVA,ALYSSON,CAIXA,FSA,11,JAN,2026,ADMISSÃO,Finalizado
PAULA ROBERTA SANTOS DOS ANJOS,ALYSSON,BALCONISTA,FSA,14,JAN,2026,ADMISSÃO,Finalizado
LUCAS CRUZ DA PAIXAO,MAICON,CAIXA,SSA,20,JAN,2026,ADMISSÃO,Finalizado
REIGIANE MATOS DOS SANTOS SILVA,MAICON,BALCONISTA,JAC,28,JAN,2026,ADMISSÃO,Finalizado
KAIQUE PORTO SANTIAGO SOUZA,MARCELLO,BALCONISTA,CAC,5,JAN,2026,ADMISSÃO,Finalizado
INGRID ALVES DOS SANTOS,RAFAEL,CAIXA,SSA,12,JAN,2026,ADMISSÃO,Finalizado
EVELLY SANTOS MACHADO,MARCELLO,CAIXA,FSA,15,JAN,2026,ADMISSÃO,Finalizado
MARIA CLARA GODINHO DOS SANTOS,MARCELLO,CAIXA,FSA,7,JAN,2026,ADMISSÃO,Finalizado
SELMA PEREIRA CARVALHO,MARCELLO,BALCONISTA,FSA,7,JAN,2026,ADMISSÃO,Finalizado
EMILY DOS REIS ALMEIDA,MARCELLO,BALCONISTA,FSA,15,JAN,2026,ADMISSÃO,Finalizado
FRANCISCO GUSTAVO DA SILVA,MAICON,BALCONISTA,SSA,17,JAN,2026,ADMISSÃO,Finalizado
ANA CATARINA DA SILVA NASCIMENTO,RAFAEL,CAIXA,SSA,25,JAN,2026,ADMISSÃO,Finalizado
JEFFERSON DOS SANTOS SOUZA SANTANA,MARCELLO,BALCONISTA,CAC,5,FEV,2026,ADMISSÃO,Finalizado
BARBARA LARISSA SANTOS DA CONCEICAO,MARCELLO,CAIXA,SAJ,24,FEV,2026,ADMISSÃO,Finalizado
EDGAR REIS DE SANTANA NETO,RAFAEL,CAIXA,SSA,25,FEV,2026,ADMISSÃO,Finalizado
JOAO VICTOR NASCIMENTO SOUZA,ALYSSON,BALCONISTA,FSA,14,FEV,2026,ADMISSÃO,Finalizado
LUNA CARLA BARBOSA SANTOS CARDOSO,MAICON,CAIXA,SSA,23,FEV,2026,ADMISSÃO,Finalizado
TAYNA PEREIRA DE SOUZA,MAICON,CAIXA,SSA,19,FEV,2026,ADMISSÃO,Finalizado
LUDMILA CARVALHO DE JESUS SANTOS,MAICON,CAIXA,SSA,20,FEV,2026,ADMISSÃO,Finalizado
ANDRE DE JESUS SUZART,MAICON,CAIXA,SSA,31,FEV,2026,ADMISSÃO,Finalizado
ALANE PEREIRA OLIVEIRA,ALYSSON,CAIXA,FSA,3,FEV,2026,ADMISSÃO,Finalizado
ANDREIA ALVES SOARES,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO,Finalizado
ARLENE LISBOA JORDAO,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO,Finalizado
EMANUELE BACELLAR GONCALVES,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO,Finalizado
DAYSE ALMEIDA FREIRES,RAFAEL,CAIXA,SSA,12,FEV,2026,ADMISSÃO,Finalizado
DENISE FERREIRA SANTOS,RAFAEL,BALCONISTA,SSA,12,FEV,2026,ADMISSÃO,Finalizado
OHANA TEIXEIRA DA SILVA,MARCELLO,CAIXA,VAL,16,FEV,2026,ADMISSÃO,Finalizado
JESSICA SANTOS DA SILVA,MARCELLO,BALCONISTA,FSA,1,FEV,2026,ADMISSÃO,Finalizado
JANINE SANTOS FERREIRA,ALYSSON,BALCONISTA,FSA,13,FEV,2026,ADMISSÃO,Finalizado
LUANA DE ALMEIDA SANTOS,RAFAEL,CAIXA,SSA,21,MAR,2026,ADMISSÃO,Finalizado
GEOVANA BITENCOURT,RAFAEL,CAIXA,SSA,25,MAR,2026,ADMISSÃO,Finalizado
VALERIA CERQUEIRA DE CARVALHO ALMEIDA,ALYSSON,CAIXA,FSA,14,MAR,2026,ADMISSÃO,Finalizado
GABRIEL DOS SANTOS SILVA,RAFAEL,CAIXA,SSA,22,MAR,2026,ADMISSÃO,Finalizado
JOSE MENDES XAVIER,ALYSSON,CAIXA,FSA,3,MAR,2026,ADMISSÃO,Finalizado
ISABELLE DE SOUZA SANTOS,ALYSSON,CAIXA,FSA,2,MAR,2026,ADMISSÃO,Finalizado
CAMILE DO ESPIRITO SANTO BISPO,MARCELLO,CAIXA,SAJ,27,MAR,2026,ADMISSÃO,Finalizado
TAINA NASCIMENTO DOS SANTOS SILVA,ALYSSON,BALCONISTA,FSA,13,MAR,2026,ADMISSÃO,Finalizado
SILMARA SANTOS BARBOSA,ALYSSON,BALCONISTA,FSA,13,MAR,2026,ADMISSÃO,Finalizado
EMYLE DA SILVA RIBEIRO,MARCELLO,BALCONISTA,FSA,7,MAR,2026,ADMISSÃO,Finalizado
EMILLY BRANDRAO DUARTE,MARCELLO,CAIXA,VAL,16,MAR,2026,ADMISSÃO,Finalizado
ISABELLA GIOVANNA CARVALHO LIMA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,ABR,2026,ADMISSÃO,Finalizado
JENIFER DE JESUS GOMES DA SILVA,RAFAEL,CAIXA,SSA,12,ABR,2026,ADMISSÃO,Finalizado
RAIANE EVILLYN DE JESUS SANTOS DE SOUZA,MAICON,CAIXA,SSA,17,ABR,2026,ADMISSÃO,Finalizado
PEDRO PAULO MARTINS GOMES DA SILVA,MAICON,CAIXA,SSA,18,ABR,2026,ADMISSÃO,Finalizado
EMILLY GOMES SANTANA,MAICON,BALCONISTA,SSA,28,ABR,2026,ADMISSÃO,Finalizado
LAISA KELLY SANTANA SANTOS,ALYSSON,BALCONISTA,FSA,3,ABR,2026,ADMISSÃO,Finalizado
RAYANE CARAPIA DOS SANTOS,RAFAEL,BALCONISTA,SSA,12,ABR,2026,ADMISSÃO,Finalizado
ELIANA DE MENEZES MADUREIRA,MAICON,CAIXA,SSA,23,ABR,2026,ADMISSÃO,Finalizado
ELIZABETE SANTANA DA SILVA,MAICON,BALCONISTA,JAC,28,ABR,2026,ADMISSÃO,Finalizado
CRISTIANE DE ALMEIDA SANTOS,MAICON,BALCONISTA,SSA,31,ABR,2026,ADMISSÃO,Finalizado
DJALMA DA HORA SILVA JUNIOR,RAFAEL,BALCONISTA,SSA,22,ABR,2026,ADMISSÃO,Finalizado
JANAI DE SOUZA PEREIRA,RAFAEL,BALCONISTA,SSA,10,ABR,2026,ADMISSÃO,Finalizado
ALICE BARBOSA LISBOA,RAFAEL,CAIXA,SSA,21,ABR,2026,ADMISSÃO,Finalizado
REBECA NUNES DOS SANTOS,RAFAEL,CAIXA,SSA,22,ABR,2026,ADMISSÃO,Finalizado
AMANDA ALVES SANTOS,ALYSSON,CAIXA,FSA,13,MAI,2026,ADMISSÃO,Exame ASO pendente
WENDEL SILVA DE OLIVEIRA,MAICON,CAIXA,SSA,31,MAI,2026,ADMISSÃO,Em andamento
JORGE ALBERTO BISPO DA PURIFICACAO,MAICON,BALCONISTA,SSA,31,MAI,2026,ADMISSÃO,Exame ASO pendente
SILVANA DE SOUZA,MAICON,BALCONISTA,SSA,17,MAI,2026,ADMISSÃO,Finalizado
ELIAS SANTA ROSA DA SILVA,ALYSSON,BALCONISTA,FSA,11,MAI,2026,ADMISSÃO,Em andamento
GRESIELE DOS SANTOS BONFIM,MAICON,CAIXA,SSA,23,MAI,2026,ADMISSÃO,Pendente documento
RAILANE DE JESUS SANTOS,MARCELLO,CAIXA,SAJ,27,MAI,2026,ADMISSÃO,Em andamento
JESSICA DE JESUS SANTOS,MARCELLO,CAIXA,VAL,16,MAI,2026,ADMISSÃO,Finalizado
SHELLDA BASTOS COSME,MARCELLO,BALCONISTA,FSA,1,MAI,2026,ADMISSÃO,Em andamento
ROSIANE LIMA DOS SANTOS,MAICON,BALCONISTA,SSA,19,MAI,2026,ADMISSÃO,Exame ASO pendente
FABIO FRANCISCO DOS SANTOS SILVA,ALYSSON,BALCONISTA,FSA,14,MAI,2026,ADMISSÃO,Finalizado
MAIKE TRINDADE DA SILVA SANTOS,ALYSSON,BALCONISTA,FSA,26,MAI,2026,ADMISSÃO,Em andamento
SAMANTA CAMILLY SILVA DOS SANTOS,MARCELLO,CAIXA,VAL,16,MAI,2026,ADMISSÃO,Pendente documento
DANIEL EVANGELISTA DOMINGOS DA SILVA,ALYSSON,CAIXA,FSA,8,MAI,2026,ADMISSÃO,Em andamento
LUCAS ALMEIDA DE OLIVEIRA,ALYSSON,BALCONISTA,FSA,13,MAI,2026,ADMISSÃO,Pendente
BIVANILDO DE MEDEIROS ALMEIDA,MARCELLO,GERENTE,FSA,15,MAI,2026,ADMISSÃO,Em andamento
BRUNA NERI VIEIRA,ALYSSON,CAIXA,FSA,3,MAI,2026,ADMISSÃO,Exame ASO pendente
DIJALMA DOS SANTOS JUNIOR,ALYSSON,CAIXA,FSA,11,MAI,2026,ADMISSÃO,Em andamento
JAIARA PIMENTA NASCIMENTO,ISAAC,SUPERVISOR FINANCEIRO,FSA,9,MAI,2026,ADMISSÃO,Pendente documento
PABLO HENRIQUE DOS SANTOS SANTANA,RAFAEL,CAIXA,SSA,21,MAI,2026,ADMISSÃO,Em andamento
MAIANE SOUSA COSTA,RAFAEL,FARMACEUTICO,SSA,25,JUN,2026,ADMISSÃO,Iniciado
ANA CRISTINA DA CRUZ TRIGUEIROS,MAICON,CAIXA,SSA,23,JUN,2026,ADMISSÃO,Iniciado
CAIO LUCCA DOS SANTOS RAMOS,MAICON,CAIXA,JAC,28,JUN,2026,ADMISSÃO,Pendente
KLEBER DOS SANTOS BARBOSA,MARCELLO,FARMACEUTICO,SSA,29,JUN,2026,ADMISSÃO,Iniciado`;
