/**
 * data.js — Dados embutidos de fallback (CORRIGIDO)
 * ─────────────────────────────────────────────────────────────────────────────
 * Combina DESLIGAMENTOS e ADMISSÕES em um único CSV (window.EMBEDDED_DATA)
 * com colunas uniformes que o app.js consegue processar.
 *
 * Colunas: COLABORADOR, SUPERVISOR, CARGO, MUNICIPIO, LOJA, MES, ANO, STATUS
 *   STATUS → "DEMISSÃO" para desligamentos | "ADMISSÃO" para admissões
 *
 * Fonte: DEMISSÕES / ADMISSÕES.xlsx
 * Exportado em: 15/06/2026
 * DESLIGAMENTOS: 118 registros | ADMISSÕES: 101 registros
 */

window.EMBEDDED_DATA = `COLABORADOR,SUPERVISOR,CARGO,MUNICIPIO,LOJA,MES,ANO,STATUS
LILIAN DE SOUZA BARRETO DA SILVA,ALYSSON,BALCONISTA,FSA,4,OUT,2025,DEMISSÃO
FERNANDA BATISTA DOS SANTOS,MAICON,CAIXA,SSA,20,OUT,2025,DEMISSÃO
CATIA PEREIRA GONCALVES,MARCELLO,BALCONISTA,FSA,1,NOV,2025,DEMISSÃO
DANIELA NASCIMENTO SANTANA,MARCELLO,BALCONISTA,SAJ,24,NOV,2025,DEMISSÃO
ESDRAS FERREIRA DOS SANTOS,MARCELLO,BALCONISTA,SAJ,24,NOV,2025,DEMISSÃO
JANAINA JESUS DA SILVA,MAICON,BALCONISTA,SSA,18,NOV,2025,DEMISSÃO
JANIO SILVA NERY,RAFAEL,BALCONISTA,SSA,10,NOV,2025,DEMISSÃO
SALOME DE OLIVEIRA BATISTA,ALYSSON,CAIXA,FSA,13,NOV,2025,DEMISSÃO
JOANA SOARES RODRIGUES,MARCELLO,BALCONISTA,SAJ,6,NOV,2025,DEMISSÃO
RAFAEL AZEVEDO VITORIA,MAICON,FARMACEUTICO,SSA,20,NOV,2025,DEMISSÃO
GABRIEL COSTA BACELAR,MARCELLO,CAIXA,FSA,15,NOV,2025,DEMISSÃO
SIDINEA REIS DOS SANTOS,MAICON,BALCONISTA,SSA,20,NOV,2025,DEMISSÃO
EMANUELLE VITORIA DA CONCEICAO CUNHA EVANGELISTA,ALYSSON,CAIXA,FSA,13,NOV,2025,DEMISSÃO
VIVIANE REIS MASCARENHAS,ALYSSON,BALCONISTA,FSA,8,NOV,2025,DEMISSÃO
MARCIA DE JESUS FERREIRA,RAFAEL,BALCONISTA,SSA,22,NOV,2025,DEMISSÃO
UESLEI CARVALHO DE OLIVEIRA DOS SANTOS,MAICON,CAIXA,SSA,17,NOV,2025,DEMISSÃO
BIANCA MARQUES SILVA,MAICON,CAIXA,SSA,23,NOV,2025,DEMISSÃO
LAISA GRASIELE SANTOS DE OLIVEIRA,MAICON,BALCONISTA,SSA,20,DEZ,2025,DEMISSÃO
ELIZANA DE MATOS MIRANDA DOS SANTOS,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,DEMISSÃO
SAMARA DOS SANTOS VIEIRA,RAFAEL,CAIXA,SSA,12,DEZ,2025,DEMISSÃO
PEDRO GILBERTO PIRES DE ARAGAO NETO,RAFAEL,CAIXA,SSA,25,DEZ,2025,DEMISSÃO
NICOLE GABRIELE BRANDI BARBOZA,ALYSSON,CAIXA,FSA,11,DEZ,2025,DEMISSÃO
DANIEL COUTINHO NERES DE JESUS,ALYSSON,GERENTE,FSA,3,DEZ,2025,DEMISSÃO
BIANCA BARBOSA DE OLIVEIRA,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,DEMISSÃO
EMILLY CORREIA OLIVEIRA,ALYSSON,CAIXA,FSA,13,DEZ,2025,DEMISSÃO
ABRAAO BATISTA SANTOS,MAICON,CAIXA,SSA,20,DEZ,2025,DEMISSÃO
ELISANGELA SANTOS SILVA,MARCELLO,BALCONISTA,SAJ,6,DEZ,2025,DEMISSÃO
MARILIA DE SANTANA SOUZA,MAICON,BALCONISTA,SSA,17,DEZ,2025,DEMISSÃO
JAISMILE DO NASCIMENTO SAMPAIO GUERRA,MARCELLO,BALCONISTA,FSA,1,DEZ,2025,DEMISSÃO
AMANDA SOUZA ROLIM,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,DEMISSÃO
IEDA BARBOSA DE JESUS SANTOS,RAFAEL,BALCONISTA,SSA,12,DEZ,2025,DEMISSÃO
GUILHERME PEREIRA CERQUEIRA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,DEZ,2025,DEMISSÃO
MAURICIO PAIXAO SERRA SOUZA,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,DEMISSÃO
LAIS STEPHANIE SILVA DANTAS,ALYSSON,CAIXA,FSA,13,DEZ,2025,DEMISSÃO
PEDRO PAULO SOUZA LOBO,MARCELLO,BALCONISTA,SAJ,24,DEZ,2025,DEMISSÃO
RAYANE REIS CUNHA CERQUEIRA,ALYSSON,FARMACEUTICO,FSA,8,DEZ,2025,DEMISSÃO
SUZANA SANTOS DA SILVA,RAFAEL,FARMACEUTICO,SSA,12,JAN,2026,DEMISSÃO
VINICIUS EDUARDO CERQUEIRA SANTOS,MARCELLO,CAIXA,FSA,15,JAN,2026,DEMISSÃO
BARBARA DE ARAUJO SILVA,ALYSSON,CAIXA,FSA,8,JAN,2026,DEMISSÃO
CLAUDIO ALBUQUERQUE BRITO SILVA,ALYSSON,BALCONISTA,FSA,14,JAN,2026,DEMISSÃO
IVIA RIBEIRO DE JESUS,RAFAEL,BALCONISTA,SSA,21,JAN,2026,DEMISSÃO
CRELIO JOSE SANTANA,MAICON,FARMACEUTICO,SSA,23,JAN,2026,DEMISSÃO
PALOMA MACEDO DE SANTANA,ALYSSON,BALCONISTA,FSA,2,JAN,2026,DEMISSÃO
JULIANA SILVA DE ASSIS,MARCELLO,CAIXA,SAJ,24,JAN,2026,DEMISSÃO
JULIA DOS SANTOS FARIAS,RAFAEL,BALCONISTA,SSA,25,JAN,2026,DEMISSÃO
LAIZA PRAXEDES DOS SANTOS MARTINS,RAFAEL,CAIXA,SSA,10,JAN,2026,DEMISSÃO
DIEGO CHAVES DA SILVA,RAFAEL,GERENTE,SSA,30,JAN,2026,DEMISSÃO
VALERIA SANTOS SOUZA,MARCELLO,BALCONISTA,CAC,5,JAN,2026,DEMISSÃO
INGRID ALVES DOS SANTOS,RAFAEL,CAIXA,SSA,12,FEV,2026,DEMISSÃO
QUEZIA GABRIELLE CARDIM SANTOS,MARCELLO,BALCONISTA,VAL,16,FEV,2026,DEMISSÃO
AMANDA SILVA OLIVEIRA,MARCELLO,CAIXA,SAJ,27,FEV,2026,DEMISSÃO
JOAO GABRIEL NUNES MOREIRA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,DEMISSÃO
DAVI GOES DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,FEV,2026,DEMISSÃO
JEREMIAS PRAZERES SALES SANTOS,ALYSSON,CAIXA,FSA,11,FEV,2026,DEMISSÃO
MIRIAN PEREIRA DE OLIVEIRA,MARCELLO,BALCONISTA,FSA,15,MAR,2026,DEMISSÃO
CARLOS DANIEL SANTOS ALMEIDA,MARCELLO,BALCONISTA,FSA,1,MAR,2026,DEMISSÃO
JULIANA SILVA DOS SANTOS,MARCELLO,BALCONISTA,SAJ,27,MAR,2026,DEMISSÃO
TIELLE VICTORIA DIAS DOS SANTOS,MAICON,BALCONISTA,SSA,23,MAR,2026,DEMISSÃO
ANA PAULA BASTOS DE OLIVEIRA,MAICON,BALCONISTA,SSA,17,MAR,2026,DEMISSÃO
ERIVALDO BRASILEIRO VITOR,MAICON,BALCONISTA,SSA,19,MAR,2026,DEMISSÃO
ATANASIA TRINDADE CONCEICAO,RAFAEL,BALCONISTA,SSA,21,MAR,2026,DEMISSÃO
JURANDIR BRITO RIBEIRO,RAFAEL,BALCONISTA,SSA,12,MAR,2026,DEMISSÃO
FERNANDA GONCALVES DIAS,MAICON,BALCONISTA,SSA,18,MAR,2026,DEMISSÃO
JONATHAS RIBEIRO PEREIRA,MARCELLO,BALCONISTA,VAL,29,MAR,2026,DEMISSÃO
JAILZA CARVALHO DE ALMEIDA,ALYSSON,BALCONISTA,FSA,4,MAR,2026,DEMISSÃO
JILVANICE SILVA DO NASCIMENTO,ALYSSON,BALCONISTA,FSA,4,MAR,2026,DEMISSÃO
JAMILE SILVA DE SENA,ALYSSON,BALCONISTA,FSA,8,MAR,2026,DEMISSÃO
PABLINE DE JESUS DA CRUZ,ALYSSON,BALCONISTA,FSA,8,MAR,2026,DEMISSÃO
ALANE PEREIRA OLIVEIRA,ALYSSON,BALCONISTA,FSA,3,MAR,2026,DEMISSÃO
DANIEL CAVALCANTE BORGES,ALYSSON,BALCONISTA,FSA,13,MAR,2026,DEMISSÃO
MARIA EDUARDA CARVALHO DOS SANTOS,MAICON,BALCONISTA,SSA,17,MAR,2026,DEMISSÃO
ANDREY DE ABREU GUSMAO,RAFAEL,BALCONISTA,SSA,12,MAR,2026,DEMISSÃO
OHANA TEIXEIRA DA SILVA,MARCELLO,BALCONISTA,FSA,15,MAR,2026,DEMISSÃO
REIGIANE MATOS DOS SANTOS SILVA,MAICON,BALCONISTA,JAC,28,MAR,2026,DEMISSÃO
BRENDA FIGUEIREDO SANTO ROCHA SILVA,MAICON,CAIXA,SSA,23,MAR,2026,DEMISSÃO
VITORIA CRUZ BASTOS,ALYSSON,BALCONISTA,FSA,14,MAR,2026,DEMISSÃO
DEISIANE CRISTINA SANTOS DA SILVA DOS SANTOS,RAFAEL,BALCONISTA,SSA,12,ABR,2026,DEMISSÃO
RITA DE CASSIA SILVA SANTOS,ISAAC,BALCONISTA,FSA,9,ABR,2026,DEMISSÃO
ANDRE COSTA MORAIS,RAFAEL,GERENTE,SSA,25,ABR,2026,DEMISSÃO
GEOVANA SILVA SANTANA,MAICON,BALCONISTA,JAC,28,ABR,2026,DEMISSÃO
CAIO ARTUR BARRETO DOS SANTOS,MARCELLO,CAIXA,FSA,1,ABR,2026,DEMISSÃO
IARA DE FREITAS MOREIRA,RAFAEL,BALCONISTA,SSA,30,ABR,2026,DEMISSÃO
EMILY PAIM SOUSA MARTINS,MAICON,CAIXA,SSA,31,ABR,2026,DEMISSÃO
ALEXSANDRO GOUVEIA FRANCO,MAICON,CAIXA,SSA,18,ABR,2026,DEMISSÃO
EMILY DOS REIS ALMEIDA,MARCELLO,CAIXA,FSA,15,ABR,2026,DEMISSÃO
KARINE SACRAMENTO GARRIDO,MARCELLO,CAIXA,SAJ,24,ABR,2026,DEMISSÃO
JEFFERSON VIEIRA BOAVENTURA,MARCELLO,CAIXA,VAL,29,ABR,2026,DEMISSÃO
GABRIEL DOS SANTOS SILVA,RAFAEL,CAIXA,SSA,22,ABR,2026,DEMISSÃO
JESSICA SANTOS DA SILVA,MARCELLO,CAIXA,FSA,1,ABR,2026,DEMISSÃO
MARIA PAULA DE OLIVEIRA DIAS,ALYSSON,CAIXA,FSA,8,ABR,2026,DEMISSÃO
CARLOS ROBERTO OLIVEIRA BOTELHO,RAFAEL,CAIXA,SSA,22,ABR,2026,DEMISSÃO
EUGENIO LUCAS MELO SILVA,ALYSSON,BALCONISTA,FSA,14,MAR,2026,DEMISSÃO
DEILSON NIEL DA PAIXAO SILVA,MAICON,BALCONISTA,SSA,18,MAI,2026,DEMISSÃO
JOSELILYAN DOS SANTOS BRAGA,MARCELLO,BALCONISTA,VAL,29,MAI,2026,DEMISSÃO
LETICIA DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,MAI,2026,DEMISSÃO
EVELYN SANTOS REIS,ALYSSON,CAIXA,FSA,4,MAI,2026,DEMISSÃO
EVERTON DOS SANTOS FERREIRA,ALYSSON,CAIXA,FSA,14,MAI,2026,DEMISSÃO
MARIA VITORIA LIMA DA SILVA,ALYSSON,CAIXA,FSA,11,MAI,2026,DEMISSÃO
DJALMA DA HORA SILVA JUNIOR,RAFAEL,CAIXA,SSA,10,MAI,2026,DEMISSÃO
WELBER SANTOS PLINIO JUNIOR,RAFAEL,BALCONISTA,SSA,30,MAI,2026,DEMISSÃO
GIRLENE SILVA DO EVANGELHO,ISAAC,ADMINISTRATIVO,FSA,9,MAI,2026,DEMISSÃO
MACIA VITAL BENTO,MAICON,BALCONISTA,SSA,17,MAI,2026,DEMISSÃO
LUDMILA CARVALHO DE JESUS SANTOS,MAICON,CAIXA,SSA,20,MAI,2026,DEMISSÃO
LUNA CARLA BARBOSA SANTOS CARDOSO,MAICON,CAIXA,SSA,23,MAI,2026,DEMISSÃO
ANDRE DE JESUS SUZART,RAFAEL,CAIXA,SSA,30,MAI,2026,DEMISSÃO
ANA CATARINA DA SILVA NASCIMENTO,RAFAEL,CAIXA,SSA,25,MAI,2026,DEMISSÃO
JEFFERSON DOS SANTOS SOUZA SANTANA,MARCELLO,BALCONISTA,CAC,5,MAI,2026,DEMISSÃO
SILMARA SANTOS BARBOSA,ALYSSON,BALCONISTA,FSA,13,MAI,2026,DEMISSÃO
ELIZABETE SANTANA DA SILVA,MARCELLO,BALCONISTA,VAL,29,MAI,2026,DEMISSÃO
EMANUELLE DE OLIVEIRA,RAFAEL,BALCONISTA,SSA,12,MAI,2026,DEMISSÃO
MARIA EDUARDA ALVES MORAIS,MARCELLO,BALCONISTA,FSA,15,MAI,2026,DEMISSÃO
ROSEKELLY RODRIGUES RIBEIRO,MARCELLO,CAIXA,FSA,1,JUN,2026,DEMISSÃO
NAYANA DHENYFER CARVALHO DOS SANTOS,MARCELLO,BALCONISTA,SAJ,27,JUN,2026,DEMISSÃO
LORENA NICOLY SOUZA SAMPAIO DE ALMEIDA,ALYSSON,BALCONISTA,FSA,26,JUN,2026,DEMISSÃO
YASMIN CERQUEIRA SOBRAL,ALYSSON,CAIXA,FSA,26,JUN,2026,DEMISSÃO
BEATRIZ RAVELLY BOAVENTURA BARNABE,ALYSSON,BALCONISTA,FSA,3,JUN,2026,DEMISSÃO
CAMILA OLIVEIRA CHAVES,ALYSSON,BALCONISTA,FSA,3,JUN,2026,DEMISSÃO
RAISSA KELLY CARVALHO MOREIRA,ALYSSON,BALCONISTA,FSA,11,JUN,2026,DEMISSÃO
IARA NEVES DE CARVALHO,MAICON,CAIXA,SSA,23,NOV,2025,ADMISSÃO
DEILSON NIEL DA PAIXAO SILVA,MAICON,BALCONISTA,SSA,17,NOV,2025,ADMISSÃO
MARIA EDUARDA CARVALHO,RAFAEL,BALCONISTA,SSA,22,NOV,2025,ADMISSÃO
LAIZA PRAXEDES DOS SANTOS MARTINS,RAFAEL,CAIXA,SSA,10,NOV,2025,ADMISSÃO
LIVIA DE ATAIDE DOS SANTOS,MAICON,CAIXA,SSA,18,NOV,2025,ADMISSÃO
ELISANGELA SANTO SILVA,MARCELLO,BALCONISTA,SAJ,6,NOV,2025,ADMISSÃO
ISYS GABRIELY REBOUCAS CONCEICAO,MARCELLO,CAIXA,SAJ,6,NOV,2025,ADMISSÃO
ELLEN VICTORIA PEREIRA FREITAS,ALYSSON,CAIXA,FSA,13,NOV,2025,ADMISSÃO
AMANDA SOUZA ROLIM,ALYSSON,CAIXA,FSA,8,DEZ,2025,ADMISSÃO
LILIAN DA LUZ SANTOS,ALYSSON,BALCONISTA,FSA,8,DEZ,2025,ADMISSÃO
BARBARA SUELLEN MORENO LEAO DOS SANTOS EVANGELISTA,ALYSSON,CAIXA,FSA,11,DEZ,2025,ADMISSÃO
JEREMIAS PRAZERES SALES SANTOS,ALYSSON,BALCONISTA,FSA,11,DEZ,2025,ADMISSÃO
LUDYMILLA SENA DO NASCIMENTO,MARCELLO,CAIXA,FSA,15,DEZ,2025,ADMISSÃO
ANDRE COSTA MORAIS,RAFAEL,BALCONISTA,SSA,25,DEZ,2025,ADMISSÃO
LILIAN DA LUZ SANTOS,MARCELLO,BALCONISTA,FSA,7,DEZ,2025,ADMISSÃO
DAVI GOES DA SILVA CRUZ,ALYSSON,CAIXA,FSA,3,DEZ,2025,ADMISSÃO
AMANDA SOUZA ROLIM,ALYSSON,CAIXA,FSA,8,DEZ,2025,ADMISSÃO
THAYNA SILVA DE SOUSA,MARCELLO,CAIXA,FSA,1,DEZ,2025,ADMISSÃO
KAMILY NUNES DOS SANTOS,MARCELLO,CAIXA,SAJ,6,DEZ,2025,ADMISSÃO
MIGUEAS SANTANA SILVA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,DEZ,2025,ADMISSÃO
VALERIA SANTOS SOUZA,MARCELLO,BALCONISTA,CAC,5,DEZ,2025,ADMISSÃO
EDUARDO SOUZA NEVES,MARCELLO,BALCONISTA,SAJ,24,DEZ,2025,ADMISSÃO
MARIELLE DE JESUS MOREIRA,ALYSSON,BALCONISTA,FSA,13,DEZ,2025,ADMISSÃO
MARIA VITORIA LIMA DA SILVA,ALYSSON,CAIXA,FSA,11,JAN,2026,ADMISSÃO
PAULA ROBERTA SANTOS DOS ANJOS,ALYSSON,BALCONISTA,FSA,14,JAN,2026,ADMISSÃO
LUCAS CRUZ DA PAIXAO,MAICON,CAIXA,SSA,20,JAN,2026,ADMISSÃO
REIGIANE MATOS DOS SANTOS SILVA,MAICON,BALCONISTA,JAC,28,JAN,2026,ADMISSÃO
KAIQUE PORTO SANTIAGO SOUZA,MARCELLO,BALCONISTA,CAC,5,JAN,2026,ADMISSÃO
INGRID ALVES DOS SANTOS,RAFAEL,CAIXA,SSA,12,JAN,2026,ADMISSÃO
EVELLY SANTOS MACHADO,MARCELLO,CAIXA,FSA,15,JAN,2026,ADMISSÃO
MARIA CLARA GODINHO DOS SANTOS,MARCELLO,CAIXA,FSA,7,JAN,2026,ADMISSÃO
SELMA PEREIRA CARVALHO,MARCELLO,BALCONISTA,FSA,7,JAN,2026,ADMISSÃO
EMILY DOS REIS ALMEIDA,MARCELLO,BALCONISTA,FSA,15,JAN,2026,ADMISSÃO
FRANCISCO GUSTAVO DA SILVA,MAICON,BALCONISTA,SSA,17,JAN,2026,ADMISSÃO
ANA CATARINA DA SILVA NASCIMENTO,RAFAEL,CAIXA,SSA,25,JAN,2026,ADMISSÃO
JEFFERSON DOS SANTOS SOUZA SANTANA,MARCELLO,BALCONISTA,CAC,5,FEV,2026,ADMISSÃO
BARBARA LARISSA SANTOS DA CONCEICAO,MARCELLO,CAIXA,SAJ,24,FEV,2026,ADMISSÃO
EDGAR REIS DE SANTANA NETO,RAFAEL,CAIXA,SSA,25,FEV,2026,ADMISSÃO
JOAO VICTOR NASCIMENTO SOUZA,ALYSSON,BALCONISTA,FSA,14,FEV,2026,ADMISSÃO
LUNA CARLA BARBOSA SANTOS CARDOSO,MAICON,CAIXA,SSA,23,FEV,2026,ADMISSÃO
TAYNA PEREIRA DE SOUZA,MAICON,CAIXA,SSA,19,FEV,2026,ADMISSÃO
LUDMILA CARVALHO DE JESUS SANTOS,MAICON,CAIXA,SSA,20,FEV,2026,ADMISSÃO
ANDRE DE JESUS SUZART,MAICON,CAIXA,SSA,31,FEV,2026,ADMISSÃO
ALANE PEREIRA OLIVEIRA,ALYSSON,CAIXA,FSA,3,FEV,2026,ADMISSÃO
ANDREIA ALVES SOARES,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO
ARLENE LISBOA JORDAO,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO
EMANUELE BACELLAR GONCALVES,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,FEV,2026,ADMISSÃO
DAYSE ALMEIDA FREIRES,RAFAEL,CAIXA,SSA,12,FEV,2026,ADMISSÃO
DENISE FERREIRA SANTOS,RAFAEL,BALCONISTA,SSA,12,FEV,2026,ADMISSÃO
OHANA TEIXEIRA DA SILVA,MARCELLO,CAIXA,VAL,16,FEV,2026,ADMISSÃO
JESSICA SANTOS DA SILVA,MARCELLO,BALCONISTA,FSA,1,FEV,2026,ADMISSÃO
JANINE SANTOS FERREIRA,ALYSSON,BALCONISTA,FSA,13,FEV,2026,ADMISSÃO
LUANA DE ALMEIDA SANTOS,RAFAEL,CAIXA,SSA,21,MAR,2026,ADMISSÃO
GEOVANA BITENCOURT,RAFAEL,CAIXA,SSA,25,MAR,2026,ADMISSÃO
VALERIA CERQUEIRA DE CARVALHO ALMEIDA,ALYSSON,CAIXA,FSA,14,MAR,2026,ADMISSÃO
GABRIEL DOS SANTOS SILVA,RAFAEL,CAIXA,SSA,22,MAR,2026,ADMISSÃO
JOSE MENDES XAVIER,ALYSSON,CAIXA,FSA,3,MAR,2026,ADMISSÃO
ISABELLE DE SOUZA SANTOS,ALYSSON,CAIXA,FSA,2,MAR,2026,ADMISSÃO
CAMILE DO ESPIRITO SANTO BISPO,MARCELLO,CAIXA,SAJ,27,MAR,2026,ADMISSÃO
TAINA NASCIMENTO DOS SANTOS SILVA,ALYSSON,BALCONISTA,FSA,13,MAR,2026,ADMISSÃO
SILMARA SANTOS BARBOSA,ALYSSON,BALCONISTA,FSA,13,MAR,2026,ADMISSÃO
EMYLE DA SILVA RIBEIRO,MARCELLO,BALCONISTA,FSA,7,MAR,2026,ADMISSÃO
EMILLY BRANDRAO DUARTE,MARCELLO,CAIXA,VAL,16,MAR,2026,ADMISSÃO
ISABELLA GIOVANNA CARVALHO LIMA,ISAAC,AUXILIAR DE LOGISTICA,FSA,9,ABR,2026,ADMISSÃO
JENIFER DE JESUS GOMES DA SILVA,RAFAEL,CAIXA,SSA,12,ABR,2026,ADMISSÃO
RAIANE EVILLYN DE JESUS SANTOS DE SOUZA,MAICON,CAIXA,SSA,17,ABR,2026,ADMISSÃO
PEDRO PAULO MARTINS GOMES DA SILVA,MAICON,CAIXA,SSA,18,ABR,2026,ADMISSÃO
EMILLY GOMES SANTANA,MAICON,BALCONISTA,SSA,28,ABR,2026,ADMISSÃO
LAISA KELLY SANTANA SANTOS,ALYSSON,BALCONISTA,FSA,3,ABR,2026,ADMISSÃO
RAYANE CARAPIA DOS SANTOS,RAFAEL,BALCONISTA,SSA,12,ABR,2026,ADMISSÃO
ELIANA DE MENEZES MADUREIRA,MAICON,CAIXA,SSA,23,ABR,2026,ADMISSÃO
ELIZABETE SANTANA DA SILVA,MAICON,BALCONISTA,JAC,28,ABR,2026,ADMISSÃO
CRISTIANE DE ALMEIDA SANTOS,MAICON,BALCONISTA,SSA,31,ABR,2026,ADMISSÃO
DJALMA DA HORA SILVA JUNIOR,RAFAEL,BALCONISTA,SSA,22,ABR,2026,ADMISSÃO
JANAI DE SOUZA PEREIRA,RAFAEL,BALCONISTA,SSA,10,ABR,2026,ADMISSÃO
ALICE BARBOSA LISBOA,RAFAEL,CAIXA,SSA,21,ABR,2026,ADMISSÃO
REBECA NUNES DOS SANTOS,RAFAEL,CAIXA,SSA,22,ABR,2026,ADMISSÃO
AMANDA ALVES SANTOS,ALYSSON,CAIXA,FSA,13,MAI,2026,ADMISSÃO
WENDEL SILVA DE OLIVEIRA,MAICON,CAIXA,SSA,31,MAI,2026,ADMISSÃO
JORGE ALBERTO BISPO DA PURIFICACAO,MAICON,BALCONISTA,SSA,31,MAI,2026,ADMISSÃO
SILVANA DE SOUZA,MAICON,BALCONISTA,SSA,17,MAI,2026,ADMISSÃO
ELIAS SANTA ROSA DA SILVA,ALYSSON,BALCONISTA,FSA,11,MAI,2026,ADMISSÃO
GRESIELE DOS SANTOS BONFIM,MAICON,CAIXA,SSA,23,MAI,2026,ADMISSÃO
RAILANE DE JESUS SANTOS,MARCELLO,CAIXA,SAJ,27,MAI,2026,ADMISSÃO
JESSICA DE JESUS SANTOS,MARCELLO,CAIXA,VAL,16,MAI,2026,ADMISSÃO
SHELLDA BASTOS COSME,MARCELLO,BALCONISTA,FSA,1,MAI,2026,ADMISSÃO
ROSIANE LIMA DOS SANTOS,MAICON,BALCONISTA,SSA,19,MAI,2026,ADMISSÃO
FABIO FRANCISCO DOS SANTOS SILVA,ALYSSON,BALCONISTA,FSA,14,MAI,2026,ADMISSÃO
MAIKE TRINDADE DA SILVA SANTOS,ALYSSON,BALCONISTA,FSA,26,MAI,2026,ADMISSÃO
SAMANTA CAMILLY SILVA DOS SANTOS,MARCELLO,CAIXA,VAL,16,MAI,2026,ADMISSÃO
DANIEL EVANGELISTA DOMINGOS DA SILVA,ALYSSON,CAIXA,FSA,8,MAI,2026,ADMISSÃO
LUCAS ALMEIDA DE OLIVEIRA,ALYSSON,BALCONISTA,FSA,13,MAI,2026,ADMISSÃO
BIVANILDO DE MEDEIROS ALMEIDA,MARCELLO,GERENTE,FSA,15,MAI,2026,ADMISSÃO
BRUNA NERI VIEIRA,ALYSSON,CAIXA,FSA,3,MAI,2026,ADMISSÃO
DIJALMA DOS SANTOS JUNIOR,ALYSSON,CAIXA,FSA,11,MAI,2026,ADMISSÃO
JAIARA PIMENTA NASCIMENTO,ISAAC,SUPERVISOR FINANCEIRO,FSA,9,MAI,2026,ADMISSÃO
PABLO HENRIQUE DOS SANTOS SANTANA,RAFAEL,CAIXA,SSA,21,MAI,2026,ADMISSÃO
MAIANE SOUSA COSTA,RAFAEL,FARMACEUTICO,SSA,25,JUN,2026,ADMISSÃO
ANA CRISTINA DA CRUZ TRIGUEIROS,MAICON,CAIXA,SSA,23,JUN,2026,ADMISSÃO
CAIO LUCCA DOS SANTOS RAMOS,MAICON,CAIXA,JAC,28,JUN,2026,ADMISSÃO
KLEBER DOS SANTOS BARBOSA,MARCELLO,FARMACEUTICO,SSA,29,JUN,2026,ADMISSÃO`;
